"""
Figure 1. (a) Conceptual framework for measuring agricultural reconstruction
under statistical system failure. (b) Conceptual framework of extensive-
and intensive-margin recovery in post-conflict livestock systems.

IMPORTANT NOTE ON PROVENANCE: Panel (a) is a manually designed schematic
(observation / identification / interpretation triangle with icons),
authored directly in a design tool rather than generated by code; it is
supplied as a static asset in data/design_assets/ and is not procedurally
reproduced here. Panel (b) -- the extensive/intensive-margin tree diagram
-- IS fully code-generated below and matches the version embedded in the
paper. This script combines the static panel (a) with the code-generated
panel (b) into the single two-panel Figure 1 used in the manuscript.

RESOLUTION NOTE: panel (b) is rendered at 600 DPI (vector-quality). Panel
(a) is a fixed static asset at its own native resolution (1386x866 px);
it is upscaled to match panel (b)'s width for composition, so panel (a)
will appear slightly softer than panel (b) when printed at large sizes.
This is an unavoidable consequence of panel (a) being a pre-existing
design asset rather than a code-generated figure (see provenance note
above). To improve panel (a)'s sharpness, replace the file in
data/design_assets/ with a higher-resolution version and re-run.

Produces: figures/Figure1_conceptual_framework.png
"""
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
import matplotlib
matplotlib.use('Agg')
import matplotlib as mpl
from PIL import Image, ImageDraw, ImageFont
from _paths import DATA_DIR, OUTPUT_DIR, FIG_DIR, FIGURE_DPI

mpl.rcParams["font.family"] = "Liberation Sans"

NAVY = "#1F4E79"
LIGHT_NAVY = "#DCE6F1"
GRAY_BOX = "#F2F2F2"
GRAY_EDGE = "#808080"
TEXT_DARK = "#1a1a1a"

# ---------------------------------------------------------------------
# Panel (b): extensive/intensive-margin conceptual framework (code-generated)
# ---------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(9.5, 11.5))
ax.set_xlim(0, 10)
ax.set_ylim(0, 12.5)
ax.axis("off")


def rounded_box(xc, yc, w, h, facecolor, edgecolor, lw=1.4, zorder=2):
    box = FancyBboxPatch((xc - w / 2, yc - h / 2), w, h,
                          boxstyle="round,pad=0.02,rounding_size=0.12",
                          linewidth=lw, edgecolor=edgecolor, facecolor=facecolor, zorder=zorder)
    ax.add_patch(box)


def arrow(x0, y0, x1, y1, color=NAVY, lw=1.8):
    a = FancyArrowPatch((x0, y0), (x1, y1), arrowstyle="-|>", mutation_scale=16,
                         linewidth=lw, color=color, shrinkA=2, shrinkB=2, zorder=1)
    ax.add_patch(a)


rounded_box(5, 11.6, 6.6, 0.9, NAVY, NAVY)
ax.text(5, 11.6, "Post-Conflict Milk Production Recovery", ha="center", va="center",
        fontsize=13.5, fontweight="bold", color="white", zorder=3)

arrow(5, 11.15, 5, 10.75, color="#555555", lw=1.6)
arrow(5, 10.75, 2.7, 10.4, color="#555555", lw=1.6)
arrow(5, 10.75, 7.3, 10.4, color="#555555", lw=1.6)

rounded_box(2.7, 8.55, 4.0, 3.6, LIGHT_NAVY, NAVY, lw=1.6)
ax.text(2.7, 9.95, "Extensive Margin", ha="center", va="center", fontsize=13, fontweight="bold", color=NAVY, zorder=3)
ax.text(2.7, 9.55, "Herd Rebuilding", ha="center", va="center", fontsize=10.5, style="italic", color=TEXT_DARK, zorder=3)
ax.text(2.7, 9.15, "(Biological Capital)", ha="center", va="center", fontsize=9.5, color="#444444", zorder=3)
for i, b in enumerate(["Restocking", "Reproduction", "Herd expansion", "Replacement"]):
    ax.text(1.15, 8.55 - i * 0.42, f"\u2022  {b}", ha="left", va="center", fontsize=10, color=TEXT_DARK, zorder=3)

rounded_box(7.3, 8.55, 4.0, 3.6, GRAY_BOX, GRAY_EDGE, lw=1.6)
ax.text(7.3, 9.95, "Intensive Margin", ha="center", va="center", fontsize=13, fontweight="bold", color="#333333", zorder=3)
ax.text(7.3, 9.55, "Yield Improvement", ha="center", va="center", fontsize=10.5, style="italic", color=TEXT_DARK, zorder=3)
ax.text(7.3, 9.15, "(Biological Productivity)", ha="center", va="center", fontsize=9.5, color="#444444", zorder=3)
for i, b in enumerate(["Nutrition", "Genetics", "Veterinary care", "Herd management"]):
    ax.text(5.75, 8.55 - i * 0.42, f"\u2022  {b}", ha="left", va="center", fontsize=10, color=TEXT_DARK, zorder=3)

arrow(2.7, 6.75, 5, 6.15, color="#555555", lw=1.6)
arrow(7.3, 6.75, 5, 6.15, color="#555555", lw=1.6)

rounded_box(5, 5.75, 6.2, 0.9, NAVY, NAVY)
ax.text(5, 5.75, "Observed Milk Production Growth", ha="center", va="center",
        fontsize=13, fontweight="bold", color="white", zorder=3)

arrow(5, 5.3, 5, 4.75, color="#555555", lw=1.6)

rounded_box(5, 3.55, 7.6, 2.1, "#FFFFFF", "#B0B0B0", lw=1.3)
ax.text(5, 4.35, "Prediction 2  (Section 2.4)", ha="center", va="center", fontsize=11.5, fontweight="bold", color=NAVY, zorder=3)
ax.text(5, 3.85, "Early recovery  \u2192  Extensive margin dominates", ha="center", va="center", fontsize=10.3, color=TEXT_DARK, zorder=3)
ax.text(5, 3.42, "Later recovery  \u2192  Intensive margin gradually increases", ha="center", va="center", fontsize=10.3, color=TEXT_DARK, zorder=3)
ax.text(5, 2.85, "(rebuilding biological capital necessarily precedes\nsustained productivity growth)",
        ha="center", va="center", fontsize=9, style="italic", color="#555555", zorder=3)

plt.tight_layout()
panel_b_path = OUTPUT_DIR / "_panel_b_temp.png"
plt.savefig(panel_b_path, dpi=FIGURE_DPI, bbox_inches="tight", facecolor="white")
plt.close(fig)

# ---------------------------------------------------------------------
# Combine static panel (a) with code-generated panel (b)
# ---------------------------------------------------------------------
panel_a_path = DATA_DIR.parent / "design_assets" / "Figure1a_measurement_framework_ORIGINAL.png"

im_a = Image.open(panel_a_path).convert("RGB")
im_b = Image.open(panel_b_path).convert("RGB")

target_w = 2400
im_a_r = im_a.resize((target_w, int(im_a.height * target_w / im_a.width)))
im_b_r = im_b.resize((target_w, int(im_b.height * target_w / im_b.width)))

label_h, gap = 50, 20
total_h = label_h + im_a_r.height + gap + label_h + im_b_r.height + 20
canvas = Image.new("RGB", (target_w + 20, total_h), "white")
draw = ImageDraw.Draw(canvas)
try:
    font = ImageFont.truetype("/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf", 32)
except OSError:
    font = ImageFont.load_default()

y = 10
draw.text((10, y), "(a) Measurement framework under statistical system failure", fill="black", font=font)
y += label_h
canvas.paste(im_a_r, (10, y))
y += im_a_r.height + gap
draw.text((10, y), "(b) Extensive- and intensive-margin recovery framework", fill="black", font=font)
y += label_h
canvas.paste(im_b_r, (10, y))

canvas.save(FIG_DIR / "Figure1_conceptual_framework.png")
panel_b_path.unlink()  # remove temp file
print("Figure 1 (two-panel composite) saved to figures/Figure1_conceptual_framework.png")
print("NOTE: panel (a) is a static design asset (data/design_assets/), not code-generated; panel (b) is code-generated above.")
